HPCC-27671 Create confidence test and key file for the General Linear Model Bundle
hpcc-systems/GLM pull request #4
Opened 2022-05-24 15:56 UTC by NSel1727

• Create a directory titled ecl which will contain test files and a key folder
• Make a new file called "FamilyTest" that takes code from the BinomialRegression file from the validation folder and makes it functional so each linear model family can be tested
• Create test files titled "xTest" where x is the name of the family being tested, that calls FamilyTest with the arguments being passed fit for that specific family
• Create a key file for each test

2022-05-24 15:57 UTC, NSel1727 commented
@AttilaVamos

2022-05-25 16:30 UTC, AttilaVamos commented on ecl/FamilyTest.ecl
> +// version tmod='Binomial'
There should no space between '//' and 'version'

2022-05-25 16:36 UTC, AttilaVamos commented on ecl/FamilyTest.ecl
> +#ElseIf(myMod = 'Quasibinomial')
Please use all capitals for '#ELSEIF' (it is coding style what we recommend).

2022-05-26 16:38 UTC, AttilaVamos commented on ecl/key/FamilyTest.xml
> +
Please remove this empty line from the key file.

2022-05-26 16:58 UTC, AttilaVamos commented on ecl/key/FamilyTest.xml
> +</Dataset>
Okay, at one '\n' (0x0A) char needed at the end of that line. I know Windows uses '\r\n' by default.

2022-05-31 15:17 UTC, NSel1727 commented
@AttilaVamos @RogerDev @ghalliday 

Please review my pull request. 

All of the seven test cases obtain the correct output but two of them go through an exception. Here is the JIRA issue: https://track.hpccsystems.com/browse/ML-513

2022-06-06 15:54 UTC, AttilaVamos requested changes
Seems good, but there are some small issues.

2022-06-06 15:54 UTC, AttilaVamos commented on ecl/FamilyTest.ecl
> +								 'sepal_length,sepal_width,petal_length,petal_width');
Indentation problem.

2022-06-06 15:54 UTC, AttilaVamos commented on ecl/FamilyTest.ecl
> +															 CHOOSE(s, t.icept_coef, t.icept_err, t.icept_pval),
Tab vs spaces (?) indentation problems.

2022-06-06 15:54 UTC, AttilaVamos commented on ecl/FamilyTest.ecl
> +errors := FamilyTest(fam, vals, classRange);
Nice use of 'classRange' variable to fix that exception problem.

2022-06-06 16:20 UTC, NSel1727 commented
@AttilaVamos

2022-06-06 16:36 UTC, AttilaVamos reviewed
I think that 8 spaces indentation is a bit wide and sometimes it makes the review hard. Usually, we use 4 spaces.  

I would split the SEQUENTIAL(...) into multiline to avoid too lengthy line. 

Please ask the others for review.

2022-06-06 16:50 UTC, ghalliday commented
> I think that 8 spaces indentation is a bit wide and sometimes it makes the review hard. Usually, we use 4 spaces.
> 
> I would split the SEQUENTIAL(...) into multiline to avoid too lengthy line.
> 
> Please ask the others for review.

I think the problem is that the file contains tabs rather than spaces - and the local tab setting is different from the 8 used by github.  The general policy is to only uses spaces for indentation to avoid the problem.

2022-06-06 17:01 UTC, NSel1727 commented
@ghalliday @RogerDev 

Please review this pull request for if it is ready to be merged.

2022-06-07 16:30 UTC, AttilaVamos approved these changes
Looks good from automated testing point of view.

2022-06-09 09:01 UTC, ghalliday commented
I had a couple of questions - use of tabs rather than spaces, and whether the copyright message is in the correct format.
@RogerDev are you happy with this - if so I'll merge.

2022-06-09 17:14 UTC, NSel1727 commented
I will update the copyright message.

2022-06-10 08:14 UTC, merged